version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_USER=poi_user
      - DB_PASSWORD=poi_password
      - DB_HOST=db
      - DB_NAME=poi_db
      - JWT_SECRET_KEY=your_jwt_secret_key
    volumes:
      - .:/app  # Mount the entire project directory
      - app_dependencies:/usr/local/lib/python3.9/site-packages 
    restart: unless-stopped 
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=poi_db
      - MYSQL_USER=poi_user
      - MYSQL_PASSWORD=poi_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped  # Automatically restart if it crashes

volumes:
  mysql_data:
  app_dependencies: 